# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_test:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    
    - name: Run security tests
      run: npm audit
      
    


  build:
    needs: security_test
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install dependancies
      run: npm install
    - name: Start the app
      run: npm run start &

    - name: Run test and save output
      run: npm run test | tee output.log
      
    - name: Upload test output as artefact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: output.log

    
